kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {
    }
    http {
      server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /www;
        server_name vbulletin;

        location / {
          location ~ \.(gif|jpg|jpeg|png|css)$ {
          }
          location = /css.php {
            rewrite ^(.*)$ /core/css.php break;
          }
          location /install {
            rewrite ^/install/ /core/install/ break;
          }
          rewrite ^/(core/libraries/|includes|core/includes|core/vb|core/vb5|core/admincp|core/modcp) /index.php?routestring=relay/404;
          rewrite (^|/)\.(?!well-known) /index.php?routestring=relay/404;
          rewrite ^/(css|fonts|images|js|core/cache|core/cpstyles|core/clientscript|core/customavatars|core/images|core/store_sitemap)/.*\.php /index.php?routestring=relay/404;
          if (!-e $request_filename){
            rewrite ^(.*)$ /index.php?routestring=$1 break;
          }
          location ~* \.php$ {
              include fastcgi_params;
              fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
              fastcgi_pass 127.0.0.1:9000;
          }
        }
    }
    }