apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: 'true'
  labels:
    app: vbulletin
  name: vbulletin
  namespace: vbulletin
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: vbulletin
  template:
    metadata:
      labels:
        app: vbulletin
    spec:
      containers:
        - env:
          - name: DATABASE
            value: vbsuite
          - name: DBUSER
            value: root
          - name: DBPASSWORD
            valueFrom:
              secretKeyRef:
                key: 'mariadb-root-password'
                name: 'vbulletin'
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          name: nginx
          resources:
            limits:
              cpu: 100m
              memory: 150Mi
            requests:
              cpu: 50m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: vbulletin
              mountPath: /www
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
        - image: devilbox/php-fpm:7.4-prod
          imagePullPolicy: IfNotPresent
          name: php
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 200m
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: vbulletin
              mountPath: /www
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
       - name: vbulletin
         persistentVolumeClaim:
           claimName: vbulletin
           readOnly: false
       - name: nginx-config-volume
         configMap:
           name: nginx-config
