apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: vbulletin
  name: vbulletin
  namespace: vbulletin
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: vbulletin
  template:
    metadata:
      labels:
        app: vbulletin
    spec:
      containers:
        - env:
          - name: DATABASE
            value: vbsuite
          - name: DBUSER
            value: vbuser
          - name: DBPASSWORD
            valueFrom:
              secretKeyRef:
                key: 'mariadb-password'
                name: 'vbulletin'
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          name: nginx
          resources:
            limits:
              cpu: 100m
              memory: 150Mi
            requests:
              cpu: 50m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: vbulletin
              mountPath: /usr/share/nginx/html
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
        - image: devilbox/php-fpm:8.2-prod
          imagePullPolicy: IfNotPresent
          name: php
          resources:
            limits:
              cpu: '5'
              memory: 4Gi
            requests:
              cpu: '2'
              memory: 2Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: vbulletin
              mountPath: /usr/share/nginx/html
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
       - name: vbulletin
         persistentVolumeClaim:
           claimName: vbulletin
           readOnly: false
       - name: nginx-config-volume
         configMap:
           name: nginx-config
