---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: php-apache
  name: php-apache
  namespace: vbulletin
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: php-apache
  template:
    metadata:
      labels:
        app: php-apache
    spec:
      initContainers:
      - name: install-php-extensions
        image: php:8-apache
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'for ext in gd mysqli hash json xml mbstring iconv curl argon2; do docker-php-ext-install $ext && docker-php-ext-enable $ext; done']
        volumeMounts:
          - name: vbulletin
            mountPath: /var/www/html
      containers:
        - env:
          - name: DATABASE
            value: vbsuite
          - name: DBUSER
            value: root
          - name: DBPASSWORD
            valueFrom:
              secretKeyRef:
                key: 'mariadb-root-password'
                name: 'vbulletin'
          - name: PORT
            value: '80'
          image: php:8-apache
          imagePullPolicy: IfNotPresent
          name: php-apache
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 500m
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: vbulletin
              mountPath: /var/www/html
              subPath: html
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
       - name: vbulletin
         persistentVolumeClaim:
           claimName: vbulletin
           readOnly: false