apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vbsuite
  namespace: vbulletin
spec:
  encryptedData:
    password: AgBO1WPufO7MYGSJvtdJFm/zkeq9kJTNsxaMZIRqFhNMyQheQgOtvLth/OaJ3NTYQSVujA1l9wG4wxbaiT131NZs1G5bllWtp78Bg5Nf9kjRwB+8dpfCf6m5koRnZiV5MgBPTQZ7JzOBKxmCcBT21SVYJpFtFRLJp0YPr3mWpRkUeV/KEgpHHE8VIfvSO2CtuiU55tNxK9yRJB3SDXcW9+aYfF8/PNLeLLzVEbJHH+n4owZ2Z2CMzyW/BJZLZJ+yaOk2IVPyR20mcElerV9+oLG2Uz12ZtNkmhkk5V98GJiM93wn9D7ev+RjCgb1U9JahlNzagftgRm9VvxrPgvLKSqpKeEyPar+02mTwgB9tdQTYO+Dt0iytUSK3oyCv0mSyMW0AOZn1Ph2uCYNN/osqHV8eUhke6vUL3OpDpdLWznKyOXUiG+WHfyZ7KMln8Zsu885RVXiqZQySNS1kxkDLWOdeWA4w9NfNPQ5WU9kxOQ2KydZwTqCdnyO9FcJK7xPs2HjPvIMOL++nkkX2MBh1Vy0pf3eq0gptd7O97mq9vy96QyoKu/4/myiLhzv7IcJEryU1uhhMiW+5ZIZ+n77vbSk7J/mDeBWwxpxElQ5aPP5+eOTXJSBPAN6mPxrPUlXpU3YsXOZh+C09FqAX4KBSBf6Ou97Zzzj3ota2KK4ADWU5yXyE5wpEbHGKqI0yh2qu4RritjQ2vg1AgbCxZlMA+4s
    username: AgBCcBc1gYL7bT0UsvaOuE20V5hwjjtN+cCbAHrpAwS2UC+2IOMaqGPe9LI+Z13Yy4Uh+FTUzYmE64Fd155EfnkCz2T/ocLGvpc7ff8Q6Wq8fqF8rBN1c4bXHcHIJo4uihVQ8xYrt1yme2Q2N3ciSqmZyft1AZ1KXCBtOCTSoDXeJzdZo2kRW3J6vzdhfaC14UI/+ojMboam3is5pcRr35VW8wpVSxIK2jjonz5ZMM/hzHDgbwT19thYGpEAm+s4YGW250U0JbYzcktVkqczHgLogeSDccq3qi0gBMQ+5k+INDB6emEOG06bBkHmXr6smtErzf0GC89+DpUFmeXH/t93H65yRstR/JKssUzOxCA75lwTtmVel0LN3Hg4wrvXv8Wnzzo7xfsxY6iwAUoRgWieVmZBN/1PC3LPOELivjOudRAJl1ZaED94IIANZaWKJH/VBqov/ZDUbPDa5R6R64IPfWsDUugRe9wUQnEuVx6cuDXAqgwbHVH8hyKSdrWkbORP7Ri9KJibGrD+pN65CR2gjAMzRht1cf1OiSqj/L3g6oGj3M61qgbqXspCPDmZkaYJ63nRjufV1I3CcGBS/OXTDYk5m7UQ+K589zvHmXXRnPJVarJdOOpXRDq+V4EXtRBPuJ3Y7q2/fPMs1Qaa4gaspOB3I6hVuMjoWWxlyw0HemNKkCFTnWimJKojjkGOD4HxM01j3QM=
  template:
    metadata:
      name: vbsuite
      namespace: vbulletin
    type: Opaque
