apiVersion: v1
kind: Service
metadata:
  labels:
    app: vbulletin
    app.kubernetes.io/instance: vbulletin
  name: vbulletin
  namespace: vbulletin
spec:
  allocateLoadBalancerNodePorts: true
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 80
      targetPort: 9000
      name: fastcgi
  selector:
    app: vbulletin
  type: LoadBalancer
