---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
    app.kubernetes.io/instance: nginx
  name: nginx
  namespace: vbulletin
spec:
  allocateLoadBalancerNodePorts: true
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
  selector:
    app: nginx
  type: LoadBalancer
---
kind: Service
apiVersion: v1
metadata:
  name: sftp
  namespace: vbulletin
  labels:
    app: sftp
spec:
  type: LoadBalancer
  ports:
  - name: ssh
    port: 22
    targetPort: 22
  selector:
    app: sftp