apiVersion: v1
kind: Service
metadata:
  labels:
    app: vbulletin
    app.kubernetes.io/instance: vbulletin
  name: vbulletin
  namespace: vbulletin
spec:
  allocateLoadBalancerNodePorts: true
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30163
    port: 80
  selector:
    app: vbulletin
  type: LoadBalancer
