---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: php
    app.kubernetes.io/instance: php
  name: php
  namespace: vbulletin
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 9000
    targetPort: 9000
    name: php
  selector:
    app: php
---
kind: Service
apiVersion: v1
metadata:
  name: sftp
  namespace: vbulletin
  labels:
    app: sftp
spec:
  type: LoadBalancer
  ports:
  - name: ssh
    port: 22
    targetPort: 22
  selector:
    app: sftp